services:
  server:
    build:
      dockerfile: Dockerfile
      context: .
    image: alkis-kalkis/server
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  caddy:
    image: caddy:2.7-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
